### PR TITLE
Add CMake build system

### PR DESCRIPTION
**Pull request by daniel-k**
This PR will add CMake as a (for now) second build system. It can build `libhermit.a` and `usr/tests` as well as `usr/benchmarks`. When you build from the top-level, tests and benchmarks will prefer the `libhermit.a` that has just been built over the one supplied with the toolchain.

Currently, it doesn't implement all the other stuff that the Makefile has, like starting Qemu or install `libhermit.a` anywhere. But this is currently at a stage where I think it can be useful and should receive some testing.

You need a recent CMake (i.e. v3.7 or up), because I wanted to use a certain feature (property `BUILDSYSTEM_TARGETS`, a pitty this has onlz now been implemented). If that's a show stopper, I can work around this.

To test this:

```bash
$ mkdir build; cd build
$ cmake ..
$ make
$ make install
```

This will build `libhermit.a` and all tests and benchmarks and copy them to `bin/tests` and `bin/benchmarks`.

**Note:** please don't merge as is, I want to squash it down to maybe 2 or 3 commits before.

### CODE REVIEW

**Comment by stlankes** [comment]
Do you also build libomp?

**Comment by daniel-k** [comment]
Now there's a script to fetch precompiled CMake binaries to satisfy our (optimistic) dependency on CMake v3.7+. It's located in `cmake/local-cmake.sh` and has to be sourced. More info in `cmake/README.md`.

I'm looking into integrating `libomp` now.

**Comment by daniel-k** [comment]
libiomp will now be built as a dependency of the applications (`tests`, `benchmarks`) see 232d868.

Please merge https://github.com/RWTH-OS/libomp_oss/pull/1 before, because this PR updates the submodule. Small changes were needed to use CMake build system of libiomp.

**Comment by daniel-k** [comment]
Furthermore `include/hermit/config.h` and `include/hermit/config.inc` will now be generated by CMake. This was missing until now. It probably has slipped through because they were still present in filesystem from previous "Make" runs.

Note: I'm using `config.status` to generate `include/hermit/config.h` because this seems to be the only possiblity right now. We may change this as soon as we get rid off the autotools stuff (in case we want to do that).

**Comment by daniel-k** [comment]
@stlankes Please try this PR on your machines. To use the new script that fetches a recent CMake binary, please have a look at c844e75.

However, this is still not finished. Neither Travis nor Debian package building uses CMake.

**Comment by daniel-k** [comment]
Ping @stlankes, any comments so far?

**Comment by stlankes** [comment]
Looks good! Do you have already updated libomp and lwip? I am not able to checkout the new versions.

**Comment by daniel-k** [comment]
@stlankes 
Quite some fixes and features today:
 - rebased onto current `devel` branch
 - building of `.deb`, `.rpm` and `.tar.bz2` packages (yet using packages is untested)
 - integration of `/tools` into top-level build system
 - integration of `usr/openmpbench`
 - ... and fixes here and there 🙂 

I would be very grateful if you could test the RPM package because I don't have any RPM-based system nor have I any experience with them.

**Comment by daniel-k** [comment]
Most things will now be built as an `ExternalProject` which has some advantages:
 - dependency on `hermit` target can now be expressed more easiliy
 - building only parts of the code with profiling (not yet implemented)
 - example how to integegrate real-world applications using HermitCore

Now there's a new include `HermitCore-Application.cmake` that is meant for user-applications, its use is demonstrated e.g. in `usr/tests/CMakeLists.txt` (which is much cleaner now).

**Comment by stlankes** [comment]
I am not an cmake expert. I try to configure the branch with` cmake -DCMAKE_INSTALL_PREFIX=/work/hermit`. But the prefix variable is the to the default path `/opt/hermit`. Consequently, I receive following errors:


```
-- The C compiler identification is unknown
-- The Fortran compiler identification is unknown
CMake Error at cmake/HermitCore.cmake:71 (enable_language):
  The CMAKE_C_COMPILER:

    /opt/hermit/bin/x86_64-hermit-gcc

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.
Call Stack (most recent call first):
  CMakeLists.txt:4 (include)
```
 How should I configure the build system?

**Comment by daniel-k** [comment]
You're not supposed to use it like this. To build, just type `cmake ..`. I'm not sure if supplying the install prefix works that way at the moment (looks like it doesn't). To deploy it somewhere, please use `make install DESTDIR=/work/hermit`

**Comment by daniel-k** [comment]
On the hand, the build system assumes that you have the HermitCore toolchain installed to `/opt/hermit` which doesn't appear to be the case. This currently a hardcoded assumption since that's the location our packages install to

**Comment by stlankes** [comment]
Is it possible to overload `TOOLCHAIN_BIN_DIR` with `cmake -DTOOLCHAIN_BIN_DIR=/work/hermit`?

**Comment by daniel-k** [comment]
Now it is. However, it fails with a rather obscure error message if you specify the wrong path. Consider this as a quick fix, will think about a solution tomorrow.

**Comment by daniel-k** [comment]
@stlankes 
I am finally done (mostly 😛). Please check the readme(s) on how to use the new build system. If you have any questions, they are very welcome and I will update the readme accordingly.

Everthing except DEB+RPM packages (they build correctly) is tested and should work. You can now also start a quick QEMU session via `make qemu` as with the old build system.

**Comment by daniel-k** [comment]
DEB package tested and works 🎉

**Comment by stlankes** [comment]
Excuse for the delay. I will check it tomorrow!

**Comment by daniel-k** [comment]
We should be ready to merge now after you approve :)

**Comment by stlankes** [comment]
Great work!

**Comment by stlankes** [comment]
@daniel-k I have an stupid. Could we create libhermit, if only the bootstrap compiler is available on my system?

**Comment by daniel-k** [comment]
Yes, that should be possible, please try `cmake ..; make hermit`

**Pull request merged**
