### PR TITLE
Various cleanup and refactoring throughout the whole codebase

### PR DESCRIPTION
**Pull request by daniel-k**
Most significantly I refactored large parts of `kernel/tasks.c` for improved readability and merging similar code paths. 

There are 2 minor bugfixes, see 1b92bcc and 3c183ec.

Furthermore, I made locks in `mm/vma`, `mm/malloc` and `kernel/syscall lwip` irqsave. Those were basically just security measures while debugging. I'm not sure if this is needed, feedback requested!

### CODE REVIEW

**Comment by stlankes** [comment]
Looks really good! But why do you protect LwIP in the syscall interface against interrupts? I don't see any reason for this.

**Comment by stlankes** [comment]
Hm, also the changes in `mm/vma`, `mm/malloc` seems for me unnecessary. We only have the requirement that any interrupt handler isn't able to use functions from these files.

**Comment by stlankes** [comment]
I slept over night and think that you are right. Especially if you start more than one task per core. That isn't the typical use case, but we should support it. I will merge the patch, after some additional checks. Thanks!

**Comment by daniel-k** [comment]
I will also have a look at it again later. At least the of having more than one task per core is not so uncommon if you start n workers on n cores. The first core will then host: master thread, lwip thread and first worker thread.

**Comment by stlankes** [comment]
Of course! But the LwIP thread isn't the problem because LwIP has its own memory management. The conflict between master and slave is the real problem...

**Comment by daniel-k** [comment]
I just had another look at it and also came to the conclusion that these locks should be irqsave. Each crticial section can be reached through a syscall, so user software might call them "concurrently".

 - `vma_alloc()` in `sys_rcce_malloc()`
 - `kmalloc()` in `sys_sem_init()`
 - LwIP communication in every forwarded syscall

**Pull request merged**
