### PR TITLE
Make devel the branch that we deploy

### PR DESCRIPTION
**Pull request by daniel-k**
I cherry-picked the commits from `production` that only existed there and made some changes to the Travis build. I think we should get rid off the `production` branches in all related repositories. It only imposes additional work keeping them synchronized and might lead to subtle problems.

Most importantly tests will be run now every time `devel` changes. This kind of counters #58, but there's no other way if we merge both branches I guess.

### CODE REVIEW

**Comment by stlankes** [comment]
Hm, you want something like a nightly builds. May idea more was to deploy the `master` branch. For me is the `devel` branch more experimental version.

**Comment by daniel-k** [comment]
But strictly speaking we cannot then use the deb-builds for checking the `devel` branch. The problem is was having with uhyve would have failed on Travis too if it had been tested.

What about additional `...-stable` deb packets that evolve with the master branch(es)?

**Comment by stlankes** [comment]
The problem isn't uhyve. Currently, I tested everything at travis with qemu. It is difficult to fix the error because it only occurs at travis. I have no problems on my test systems (with Ubuntu and CentOS).

Furthermore, I install the deb packet, which is build based on the current branch. Afterwards I build the examples and test them.

**Comment by daniel-k** [comment]
> The problem isn't uhyve.

It isn't right now, but it's part of a class of problems that will occur if you change certain parts of libhermit. In the uhyve case, changes in `entry.asm` were not propagated to `libhermit*.deb`, so if anyone uses the deb packages from Bintray, they wouldn't be able to compile the `devel` branch (me).

> It is difficult to fix the error because it only occurs at travis. I have no problems on my test systems (with Ubuntu and CentOS).

I don't really understand what you mean by this. If you refer to this branch not build at Travis, I just fixed it. Apparently you have to export the HERMIT_ variables in the bash script, see 1ffdd5e.

**Comment by stlankes** [comment]
> > The problem isn't uhyve.

> It isn't right now, but it's part of a class of problems that will occur if you change certain parts of libhermit. In the uhyve case, changes in entry.asm were not propagated to libhermit*.deb, so if anyone uses the deb packages from Bintray, they wouldn't be able to compile the devel branch (me).
> 

Yes, but is this not a typical behavior of an experimental branch? In .traviy.yml I install lib hermit*.deb, which fits to the current tests (https://github.com/RWTH-OS/HermitCore/blob/production/.travis.yml#L20-L23).

> > It is difficult to fix the error because it only occurs at travis. I have no problems on my test systems (with Ubuntu and CentOS).

> I don't really understand what you mean by this. If you refer to this branch not build at Travis, I just fixed it. Apparently you have to export the HERMIT_ variables in the bash script, see 1ffdd5e.

Maybe, we speak from different problems. Sometimes the test applications get stuck (https://api.travis-ci.org/jobs/177410668/log.txt?deansi=true) and I am not able to reproduce this behavior on my test systems. I export my HERMIT_ variables in the .travis.yml.

I want to test all branches also the `devel` and `master` branches, where the `master` is for me the stable branch. Consequently, I have no problem with your changes. The production branch is currently a workaround to create deb packages. We have to solve the problems at travis with my tests.

**Comment by stlankes** [comment]
I removed a commit and test also on the branch `production`. Look at Travic CI (https://travis-ci.org/RWTH-OS/HermitCore/builds). Three runs, two failed, one was successful. I have  not clue to explain this behavior.

**Comment by daniel-k** [comment]
Ah, now I get your point. I wasn't aware of this problem.

**Comment by stlankes** [comment]
I will merge the changes to the branches `master` & `devel` and close this requests.

**Pull request closed without merging**
