### PR TITLE
[WIP] Reimplement the HermitCore proxy in Rust

### PR DESCRIPTION
**Pull request by bytesnake**
This PR adds an initial implementation of the HermitCore proxy in Rust. There are a lot missing functionalities, especially the newer features. (e.g. snapshots) The uHyve and Multi isles aren't tested throughout yet, the qemu isle should work as expected. 
Some unfinished and rough idea outlines:
 * We could improve the tool experience with a more natural argument syntax. For example consider the following syntax: "proxy start ./hello --qemu --cpus 2". This is shorter and easier to grasp than "HERMIT_ISLE=qemu HERMIT_CPUS=2 proxy ./hello". We could also integrate the snapshots with a new subcommand like "proxy snapshot load ...". I've already talked with Stefan about this, a snapshot seems to rely on the environment variable, so we could perhaps use a hybrid method, e.g. the env variables are set by the arguments.
* The TCP protocol relies on the platform architecture. The protocol should at least recommend the de-facto standard. Perhaps it's better to use network endianness.
* The syscall protocol should have the same layout as the network protocol.

Things I'm discontent about in the new implementation:
 * missing documentation
 * the error handling is somewhat verbose, especially in combination with the IOCTL macro
 * some edges are overengineered due to the direct port from the C version

I've added some debugging output which can be activated by RUST_LOG=trace. For instance:
`RUST_LOG=trace HERMIT_ISLE=qemu ./target/debug/hermitcore_proxy ./hello`

Please feel free to report any problem you're encountering, this PR exists to get some feedback
-L

### CODE REVIEW

**Comment by stv0g** [comment]
A comment to the proposed command line arguments:

Is this supported if you register the proxy with binfmt_misc?

**Comment by bytesnake** [comment]
No this is problematic, because all arguments are passed to the binary and not the proxy. Therefore we could first check the call argument for a parameter and, if no specified, fall back to the environment variable and then the default value.

**Comment by stv0g** [comment]
Okay, as long as you still check th environment it should be fine. ☺

**Comment by stlankes** [comment]
Hello @bytesnake,

I tested your version in my HermitCore fork (https://github.com/stlankes/HermitCore/tree/proxy_rs). I moved the source files to the directory proxy and modify .travis.yml slightly to build HermitCore at TravisCI (https://travis-ci.org/stlankes/HermitCore/builds/268171494).

However, I am not able to test your proxy. Maybe I miss understood your description, but on my system I am not able to use your proxy. Could describe the proxy in more detail? Could you add  license text (MIT) to your source code?

Thanks for the support!

**Comment by bytesnake** [comment]
Hey, sorry for the delay, I was busy finishing my thesis. I'll add the license file and a README next week (probably monday), but you can always use "--help" to get an overview of the different commands.

**Comment by stlankes** [comment]
I know :-)

I build my branch and try in the build directory following command:

`local_prefix/opt/hermit/bin/proxy run -local_prefix/opt/hermit/x86_64-hermit/extra/tests/hello`

However, nothing happens...

**Comment by bytesnake** [comment]
Perhaps you are calling the wrong proxy binary? Until now the binary of Rust version is called "hermit_proxy" to differentiate them.

**Comment by stlankes** [comment]
I used slightly a modified version (see https://github.com/stlankes/HermitCore/tree/proxy_rs), where I removed the C version of our proxy. I used definitely the Rust version of the proxy.

**Comment by bytesnake** [comment]
Mh strange, can you pull the last commit, the file ldhermit was located in the wrong path. Then check if 1. "/tmp/hermit_daemon" exists 2. "proxy list" works. 3. "proxy run <sth> --isle uhyve" works.

**Comment by stlankes** [comment]
I slightly modify the proxy and merge it into the branch devel.

Thanks!

**Pull request merged**
